import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { APIService } from "../src/utils/apiService";
import styles from "../styles/Home.module.css";
import { usersUrl } from "../src/constantes/webServiceUrl";
import { GetMethod } from "../src/constantes/globalTexts";
import { useDispatch, useSelector } from "react-redux";
import { changeUserLists } from "../src/redux/users/usersActions";
import RenderUsersList from "../src/componets/users/RenderUsersList";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    // AsyncAPIService()
    getListes();
  }, []);

  const getListes = () => {
    APIService(
      usersUrl,
      GetMethod,
      {
        onSuccess(res) {
          const data = res.data;
          console.log(data);
          dispatch(changeUserLists(data));
          // setLoading(false);
        },
        onFail(err) {
          console.log(err);
          // setLoading(false);
        },
      },
      null,
      {
        useAccessToken: true,
      }
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <RenderUsersList />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
